%% Create Deep Learning Network Architecture
% Script for creating the layers for a deep learning network with the following 
% properties:
%%
% 
%  Number of layers: 14
%  Number of connections: 13
%
%% 
% Run the script to create the layers in the workspace variable |layers|.
% 
% To learn more, see <matlab:helpview('deeplearning','generate_matlab_code') 
% Generate MATLAB Code From Deep Network Designer>.
% 
% Auto-generated by MATLAB on 11-Jun-2020 17:53:49
%% Create Array of Layers

layers = [
    imageInputLayer([32 32 3],"Name","imageinput","Normalization","rescale-symmetric")
    convolution2dLayer([5 5],6,"Name","conv_1","WeightL2Factor",0)
    reluLayer("Name","relu_1")
    maxPooling2dLayer([2 2],"Name","maxpool_1","Stride",[2 2])
    convolution2dLayer([5 5],16,"Name","conv_2","WeightL2Factor",0)
    reluLayer("Name","relu_2")
    maxPooling2dLayer([2 2],"Name","maxpool_2","Stride",[2 2])
    fullyConnectedLayer(120,"Name","fc_1","WeightL2Factor",0)
    reluLayer("Name","relu_3")
    fullyConnectedLayer(84,"Name","fc_2","WeightL2Factor",0)
    reluLayer("Name","relu_4")
    fullyConnectedLayer(10,"Name","fc_3","WeightL2Factor",0)
    softmaxLayer("Name","softmax")
    classificationLayer("Name","classoutput")];
%% Plot Layers

plot(layerGraph(layers));